language: go
go:
- release
- tip

install:
- go get -v github.com/Masterminds/glide
- cd $GOPATH/src/github.com/Masterminds/glide && git checkout 245caced2b16358b1c5e267691b17e9ee9952127 && go install && cd -
- glide install

script:
- go build -o vault-vouch main.go

